srun: Step created for StepId=41589699.128
srun: Step created for StepId=41589699.129
srun: Step created for StepId=41589699.130
srun: Step created for StepId=41589699.131
srun: Step created for StepId=41589699.132
srun: Step created for StepId=41589699.133
srun: Step created for StepId=41589699.134
srun: Step created for StepId=41589699.135
srun: Step created for StepId=41589699.136
srun: Step created for StepId=41589699.137
srun: Step created for StepId=41589699.138
srun: Step created for StepId=41589699.139
srun: Step created for StepId=41589699.140
srun: Step created for StepId=41589699.141
srun: Step created for StepId=41589699.142
srun: Step created for StepId=41589699.143
srun: Step created for StepId=41589699.144
srun: Step created for StepId=41589699.145
srun: Step created for StepId=41589699.146
srun: Step created for StepId=41589699.147
srun: Step created for StepId=41589699.148
srun: Step created for StepId=41589699.149
srun: Step created for StepId=41589699.150
srun: Step created for StepId=41589699.151
srun: Step created for StepId=41589699.152
srun: Step created for StepId=41589699.153
srun: Step created for StepId=41589699.154
srun: Step created for StepId=41589699.155
srun: Step created for StepId=41589699.156
srun: Step created for StepId=41589699.157
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: error: nid006213: task 0: Exited with exit code 1
srun: Terminating StepId=41589699.30
srun: Step created for StepId=41589699.158
srun: error: nid006213: task 0: Exited with exit code 1
srun: Terminating StepId=41589699.39
srun: Step created for StepId=41589699.159
srun: Step created for StepId=41589699.160
srun: Step created for StepId=41589699.161
srun: Step created for StepId=41589699.162
srun: Step created for StepId=41589699.163
srun: Step created for StepId=41589699.164
srun: Step created for StepId=41589699.165
srun: Step created for StepId=41589699.166
srun: Step created for StepId=41589699.167
srun: Step created for StepId=41589699.168
srun: Step created for StepId=41589699.169
srun: Step created for StepId=41589699.170
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: Step created for StepId=41589699.171
srun: Step created for StepId=41589699.172
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: error: nid006213: task 0: Exited with exit code 1
srun: Terminating StepId=41589699.72
srun: Step created for StepId=41589699.173
srun: Step created for StepId=41589699.174
srun: Step created for StepId=41589699.175
srun: Step created for StepId=41589699.176
srun: Step created for StepId=41589699.177
srun: Step created for StepId=41589699.178
srun: Step created for StepId=41589699.179
srun: Step created for StepId=41589699.180
srun: Step created for StepId=41589699.181
srun: Step created for StepId=41589699.182
srun: Step created for StepId=41589699.183
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: Step created for StepId=41589699.184
srun: Step created for StepId=41589699.185
srun: Step created for StepId=41589699.186
srun: Step created for StepId=41589699.187
srun: Step created for StepId=41589699.188
srun: Step created for StepId=41589699.189
srun: Step created for StepId=41589699.190
srun: Step created for StepId=41589699.191
srun: error: nid006213: task 0: Exited with exit code 1
srun: Terminating StepId=41589699.50
srun: Step created for StepId=41589699.192
srun: Step created for StepId=41589699.193
srun: Step created for StepId=41589699.194
srun: Step created for StepId=41589699.195
srun: Step created for StepId=41589699.196
srun: Step created for StepId=41589699.197
srun: Step created for StepId=41589699.198
srun: Step created for StepId=41589699.199
srun: error: nid006213: task 0: Exited with exit code 1
srun: Terminating StepId=41589699.60
srun: Step created for StepId=41589699.200
srun: Step created for StepId=41589699.201
srun: Step created for StepId=41589699.202
srun: Step created for StepId=41589699.203
srun: Step created for StepId=41589699.204
srun: Step created for StepId=41589699.205
srun: Step created for StepId=41589699.206
srun: Step created for StepId=41589699.207
srun: Step created for StepId=41589699.208
srun: Step created for StepId=41589699.209
srun: Step created for StepId=41589699.210
srun: Step created for StepId=41589699.211
srun: Step created for StepId=41589699.212
srun: Step created for StepId=41589699.213
srun: Step created for StepId=41589699.214
srun: Step created for StepId=41589699.215
srun: Step created for StepId=41589699.216
srun: Step created for StepId=41589699.217
srun: Step created for StepId=41589699.218
srun: Step created for StepId=41589699.219
srun: Step created for StepId=41589699.220
srun: Step created for StepId=41589699.221
srun: Step created for StepId=41589699.222
srun: Step created for StepId=41589699.223
srun: Step created for StepId=41589699.224
srun: Step created for StepId=41589699.225
srun: Step created for StepId=41589699.226
srun: Step created for StepId=41589699.227
srun: Step created for StepId=41589699.228
srun: Step created for StepId=41589699.229
srun: Step created for StepId=41589699.230
srun: Step created for StepId=41589699.231
srun: Step created for StepId=41589699.232
srun: Step created for StepId=41589699.233
srun: Step created for StepId=41589699.234
srun: Step created for StepId=41589699.235
srun: Step created for StepId=41589699.236
srun: Step created for StepId=41589699.237
srun: Step created for StepId=41589699.238
srun: Step created for StepId=41589699.239
srun: Step created for StepId=41589699.240
srun: Step created for StepId=41589699.241
srun: Step created for StepId=41589699.242
srun: Step created for StepId=41589699.243
srun: Step created for StepId=41589699.244
srun: Step created for StepId=41589699.245
srun: Step created for StepId=41589699.246
srun: Step created for StepId=41589699.247
srun: Step created for StepId=41589699.248
srun: Step created for StepId=41589699.249
srun: Step created for StepId=41589699.250
srun: Step created for StepId=41589699.251
srun: Step created for StepId=41589699.252
srun: Step created for StepId=41589699.253
srun: Step created for StepId=41589699.254
srun: Step created for StepId=41589699.255
srun: Step created for StepId=41589699.256
srun: Step created for StepId=41589699.257
srun: Step created for StepId=41589699.258
srun: Step created for StepId=41589699.259
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS]
                  [--n_trs N_TRS] [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile]
                  [--fc_data_path FC_DATA_PATH] [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006213: task 0: Exited with exit code 2
srun: Terminating StepId=41589699.134
srun: Step created for StepId=41589699.260
srun: Step created for StepId=41589699.261
srun: Step created for StepId=41589699.262
srun: Step created for StepId=41589699.263
srun: Step created for StepId=41589699.264
srun: Step created for StepId=41589699.265
srun: Step created for StepId=41589699.266
srun: Step created for StepId=41589699.267
srun: Step created for StepId=41589699.268
srun: Step created for StepId=41589699.269
srun: Step created for StepId=41589699.270
srun: Step created for StepId=41589699.271
srun: Step created for StepId=41589699.272
srun: Step created for StepId=41589699.273
srun: Step created for StepId=41589699.274
srun: Step created for StepId=41589699.275
srun: Step created for StepId=41589699.276
srun: Step created for StepId=41589699.277
srun: Step created for StepId=41589699.278
srun: Step created for StepId=41589699.279
srun: Step created for StepId=41589699.280
srun: Step created for StepId=41589699.281
srun: Step created for StepId=41589699.282
srun: Step created for StepId=41589699.283
srun: Step created for StepId=41589699.284
srun: Step created for StepId=41589699.285
srun: Step created for StepId=41589699.286
srun: Step created for StepId=41589699.287
srun: Step created for StepId=41589699.288
srun: Step created for StepId=41589699.289
srun: Step created for StepId=41589699.290
srun: Step created for StepId=41589699.291
srun: Step created for StepId=41589699.292
srun: Step created for StepId=41589699.293
srun: Step created for StepId=41589699.294
srun: Step created for StepId=41589699.295
srun: Step created for StepId=41589699.296
srun: Step created for StepId=41589699.297
srun: Step created for StepId=41589699.298
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: error: nid006213: task 0: Exited with exit code 1
srun: Terminating StepId=41589699.181
srun: Step created for StepId=41589699.299
srun: Step created for StepId=41589699.300
srun: Step created for StepId=41589699.301
srun: Step created for StepId=41589699.302
srun: Step created for StepId=41589699.303
srun: Step created for StepId=41589699.304
srun: Step created for StepId=41589699.305
srun: Step created for StepId=41589699.306
srun: Step created for StepId=41589699.307
srun: Step created for StepId=41589699.308
srun: Step created for StepId=41589699.309
srun: Step created for StepId=41589699.310
srun: Step created for StepId=41589699.311
srun: Step created for StepId=41589699.312
srun: Step created for StepId=41589699.313
srun: Step created for StepId=41589699.314
srun: Step created for StepId=41589699.315
srun: Step created for StepId=41589699.316
srun: Step created for StepId=41589699.317
srun: Step created for StepId=41589699.318
srun: Step created for StepId=41589699.319
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS]
                  [--n_trs N_TRS] [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile]
                  [--fc_data_path FC_DATA_PATH] [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: error: nid006213: task 0: Exited with exit code 1
srun: Terminating StepId=41589699.185
srun: Step created for StepId=41589699.320
srun: Step created for StepId=41589699.321
srun: Step created for StepId=41589699.322
srun: Step created for StepId=41589699.323
srun: Step created for StepId=41589699.324
srun: Step created for StepId=41589699.325
srun: error: nid006213: task 0: Exited with exit code 2
srun: Terminating StepId=41589699.186
srun: Step created for StepId=41589699.326
srun: Step created for StepId=41589699.327
srun: Step created for StepId=41589699.328
srun: error: nid006213: task 0: Exited with exit code 1
srun: Terminating StepId=41589699.176
srun: Step created for StepId=41589699.329
srun: Step created for StepId=41589699.330
srun: Step created for StepId=41589699.331
srun: Step created for StepId=41589699.332
srun: Step created for StepId=41589699.333
srun: Step created for StepId=41589699.334
srun: Step created for StepId=41589699.335
srun: Step created for StepId=41589699.336
srun: Step created for StepId=41589699.337
srun: Step created for StepId=41589699.338
srun: Step created for StepId=41589699.339
srun: Step created for StepId=41589699.340
srun: Step created for StepId=41589699.341
srun: error: nid006213: task 0: Exited with exit code 1
srun: Terminating StepId=41589699.207
srun: Step created for StepId=41589699.342
srun: Step created for StepId=41589699.343
srun: Step created for StepId=41589699.344
srun: Step created for StepId=41589699.345
srun: Step created for StepId=41589699.346
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
AssertionError
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: error: nid006213: task 0: Exited with exit code 1
srun: Terminating StepId=41589699.253
srun: Step created for StepId=41589699.347
srun: Step created for StepId=41589699.348
srun: error: nid006213: task 0: Exited with exit code 1
srun: Terminating StepId=41589699.229
srun: Step created for StepId=41589699.349
srun: Step created for StepId=41589699.350
srun: Step created for StepId=41589699.351
srun: Step created for StepId=41589699.352
srun: Step created for StepId=41589699.353
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: Step created for StepId=41589699.354
srun: Step created for StepId=41589699.355
srun: Step created for StepId=41589699.356
srun: Step created for StepId=41589699.357
srun: Step created for StepId=41589699.358
srun: Step created for StepId=41589699.359
srun: Step created for StepId=41589699.360
srun: Step created for StepId=41589699.361
srun: Step created for StepId=41589699.362
srun: Step created for StepId=41589699.363
srun: Step created for StepId=41589699.364
srun: Step created for StepId=41589699.365
srun: Step created for StepId=41589699.366
srun: error: nid006213: task 0: Exited with exit code 1
srun: Terminating StepId=41589699.243
srun: Step created for StepId=41589699.367
srun: Step created for StepId=41589699.368
srun: Step created for StepId=41589699.369
srun: Step created for StepId=41589699.370
srun: Step created for StepId=41589699.371
srun: Step created for StepId=41589699.373
srun: Step created for StepId=41589699.372
srun: Step created for StepId=41589699.374
srun: Step created for StepId=41589699.375
srun: Step created for StepId=41589699.376
srun: Step created for StepId=41589699.377
srun: Step created for StepId=41589699.378
srun: Step created for StepId=41589699.379
srun: Step created for StepId=41589699.380
srun: Step created for StepId=41589699.381
srun: Step created for StepId=41589699.382
srun: Step created for StepId=41589699.383
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: error: nid006213: task 0: Exited with exit code 1
srun: Terminating StepId=41589699.256
srun: error: nid006213: task 0: Exited with exit code 1
srun: Terminating StepId=41589699.259
srun: Step created for StepId=41589699.384
srun: Step created for StepId=41589699.385
srun: Step created for StepId=41589699.386
srun: Step created for StepId=41589699.387
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: error: nid006213: task 0: Exited with exit code 1
srun: Terminating StepId=41589699.262
srun: Step created for StepId=41589699.388
srun: Step created for StepId=41589699.389
srun: Step created for StepId=41589699.390
srun: Step created for StepId=41589699.391
srun: Step created for StepId=41589699.392
srun: Step created for StepId=41589699.393
srun: Step created for StepId=41589699.394
srun: Step created for StepId=41589699.395
srun: Step created for StepId=41589699.396
srun: Step created for StepId=41589699.397
srun: Step created for StepId=41589699.398
srun: Step created for StepId=41589699.399
srun: Step created for StepId=41589699.400
srun: Step created for StepId=41589699.401
srun: Step created for StepId=41589699.402
srun: Step created for StepId=41589699.403
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS]
                  [--n_trs N_TRS] [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile]
                  [--fc_data_path FC_DATA_PATH] [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
srun: error: nid006213: task 0: Exited with exit code 2
srun: Terminating StepId=41589699.291
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: error: nid006213: task 0: Exited with exit code 1
srun: Terminating StepId=41589699.297
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: error: nid006213: task 0: Exited with exit code 1
srun: Terminating StepId=41589699.344
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: error: nid006213: task 0: Exited with exit code 1
srun: Terminating StepId=41589699.336
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
usage: calc_fc.py [-h] [--sub_id SUB_ID] [--ses_id SES_ID] [--task_id TASK_ID] [--atlas_spec ATLAS_SPEC] [--n_rois N_ROIS]
                  [--n_trs N_TRS] [--n_folds N_FOLDS] [--model MODEL] [--cv CV] [--proc_type PROC_TYPE] [--profile]
                  [--fc_data_path FC_DATA_PATH] [--max_iter MAX_ITER]
calc_fc.py: error: argument --sub_id: expected one argument
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: error: nid006213: task 0: Exited with exit code 1
srun: Terminating StepId=41589699.337
srun: error: nid006213: task 0: Exited with exit code 1
srun: Terminating StepId=41589699.382
srun: error: nid006213: task 0: Exited with exit code 2
srun: Terminating StepId=41589699.359
srun: error: nid006213: task 0: Exited with exit code 1
srun: Terminating StepId=41589699.334
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
Traceback (most recent call last):
           ^^^^^^^^^^^^^^^^^^
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
AssertionError
           ^^^^^^^^^^^^^^^^^^
AssertionError
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: error: nid006213: task 0: Exited with exit code 1
srun: Terminating StepId=41589699.380
srun: error: nid006213: task 0: Exited with exit code 1
srun: Terminating StepId=41589699.368
srun: error: nid006213: task 0: Exited with exit code 1
srun: Terminating StepId=41589699.377
srun: error: nid006213: task 0: Exited with exit code 1
srun: Terminating StepId=41589699.375
Traceback (most recent call last):
  File "/global/homes/m/mphagen/functional-connectivity/connectome-comparison/scripts/processing/calc_fc.py", line 131, in <module>
    assert len(ts_files) == 1
           ^^^^^^^^^^^^^^^^^^
AssertionError
srun: error: nid006213: task 0: Exited with exit code 1
srun: Terminating StepId=41589699.390
